{
  "swagger": "2.0",
  "info": {
    "description": "API simples de usuários",
    "version": "1.0.0",
    "title": "User API"
  },
  "paths": {
    "/users": {
      "get": {
        "summary": "Lista todos os usuários",
        "responses": {
          "200": {
            "description": "Lista de usuários",
            "schema": {
              "type": "object"
            }
          }
        }
      },
      "post": {
        "summary": "Cria um novo usuário",
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "description": "Dados do usuário",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário criado",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}
